apiVersion: apps/v1
kind: Deployment
metadata:
  name: workflow-api
  labels:
    app: workflow-api
spec:
  selector:
    matchLabels:
      app: workflow-api
  template:
    metadata:
      labels:
        app: workflow-api
    spec:
      containers:
      - name: workflow-api
        image: workflow-api-image
        ports:
        - containerPort: 8000
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
          requests:
            memory: 256Mi
            cpu: "0.2"
